import numpy as np

class MetaAgent:
    """
    Implements Marcos López de Prado's Meta-Labeling architecture.

    This agent combines a primary model (XGBoost) for directional signals (buy/sell/hold)
    with a secondary model (PPO) for risk sizing.
    """
    def __init__(self, xgb_model, ppo_model, step_size=0.1):
        """
        Initializes the MetaAgent.

        Args:
            xgb_model: Primary directional model (XGBClassifier).
            ppo_model (stable_baselines3.PPO): Secondary bet-sizing model.
            step_size (float): Discretization step for bet sizing to prevent jitter. Defaults to 0.1.
        """
        self.xgb_model = xgb_model
        self.ppo = ppo_model
        self.step_size = step_size
        self.action_space = ppo_model.action_space

    def predict(self, obs, deterministic=True):
        """
        Predicts the optimal trading action based on Meta-Labeling mathematics.

        Args:
            obs (np.ndarray): The current environment observation.
                              Expected shape: (n_envs, 4) or (4,)
                              where features are [xgb_signal, xgb_prob, rolling_volatility, portfolio_drawdown]
            deterministic (bool): Whether to use deterministic actions. Defaults to True.

        Returns:
            tuple: (action array, state/None) conforming to the Stable-Baselines3 predict signature.
        """
        # Extract the directional signal generated by the primary model (XGBoost)
        # from the environment observation.
        is_vectorized = len(obs.shape) > 1
        if is_vectorized:
            direction = obs[0, 0]
        else:
            direction = obs[0]

        # If the primary model says hold (or the signal is 0), we veto the trade
        if direction == 0.0:
            return np.array([0.0]), None

        # The secondary model (PPO) determines the continuous bet size [0.0, 1.0]
        ppo_act, _ = self.ppo.predict(obs, deterministic=deterministic)

        # Ensure the bet size is within the allowed range
        raw_size = np.clip(ppo_act[0], 0.0, 1.0)

        # Size Discretization (Thresholding to prevent jitter)
        m_discrete = np.round(raw_size / self.step_size) * self.step_size

        return np.array([m_discrete]), None
